manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: rgbatty
      url-base: https://github.com/rgbatty
  projects:
    - name: zmk
      remote: rgbatty
      revision: rollow
      import: app/west.yml
  self:
    path: config
